import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AppProvider from "@/lib/redux/Provider";
import { Rubik } from "next/font/google";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "CodeCircle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${rubik.variable} custom-font`}>
      <body suppressHydrationWarning className="overflow-x-hidden">
        <AppProvider>
          <div className="flex flex-col md:flex-row h-screen">
            {/* Sidebar for md+ screens */}
            <aside className="w-64 hidden md:flex max-lg:w-48 text-primary flex-col bg-nav border-r p-4">
              <Navbar />
            </aside>

            {/* Main Content */}
            <main className="flex-1 overflow-y-auto bg-app text-primary">
              {children}
            </main>

            {/* Bottom Navbar for smaller screens */}
            <div className="md:hidden fixed bottom-0 left-0 w-full bg-nav border-t p-2 flex justify-around text-primary z-50">
              <Navbar />
            </div>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
