import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AppProvider from "@/lib/redux/Provider";
import { Rubik } from "next/font/google";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "DevConnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${rubik.variable} custom-font`}>
      <body suppressHydrationWarning>
        <AppProvider>
          <div className="flex min-h-screen">
            {/* Sidebar */}
            <aside className="w-64 hidden md:flex text-primary flex-col bg-nav border-r p-4">
              <Navbar />
            </aside>

            {/* Main Content */}
            <main className="flex-1 overflow-y-auto bg-app text-primary">
              {children}
            </main>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
